version: "3.5"
services:
  nginx:
    restart: unless-stopped
    image: nginx
    depends_on:
      - wemx
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./${APP_DIR}:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - ${NETWORK}

networks:
  ${NETWORK}:
    external: true
