version: "3.5"
services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: php
        build:
          context: .
          dockerfile: .docker/php/Dockerfile
        depends_on:
            - db
        ports:
            - 5173:5173
        volumes:
            - ./${APP_DIR}:/var/www:cached
            - ./.docker/php/install.sh:/usr/local/bin/install.sh
            - ./.docker/php/update.sh:/usr/local/bin/update.sh
            - ./.env:/usr/local/bin/.env
        environment:
              APP_URL: ${APP_URL}
              DOMAIN: ${DOMAIN}
              DB_CONNECTION: mysql
              DB_HOST: ${DB_HOST}
              DB_PORT: ${DB_PORT}
              DB_DATABASE: ${DB_DATABASE}
              DB_USERNAME: ${DB_USERNAME}
              DB_PASSWORD: ${DB_PASSWORD}
              LICENSE_KEY: ${LICENSE_KEY}
              USERNAME: ${USERNAME}
              PASSWORD: ${PASSWORD}
              EMAIL: ${EMAIL}
              FIRST_NAME: ${FIRST_NAME}
              LAST_NAME: ${LAST_NAME}
              FORCE_HTTPS: ${FORCE_HTTPS}
              LARAVEL_CLOUDFLARE_ENABLED: ${LARAVEL_CLOUDFLARE_ENABLED}
              VERSION: ${VERSION}
              TYPE: ${TYPE}
        networks:
            - proxy

    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: nginx
        image: nginx
        depends_on:
            - php
        volumes:
            - ./${APP_DIR}:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.entrypoints=http"
            - "traefik.http.routers.nginx.rule=Host(`${DOMAIN}`)"
            - "traefik.http.middlewares.nginx-https-redirect.redirectscheme.scheme=https"
            - "traefik.http.routers.nginx.middlewares=nginx-https-redirect"
            - "traefik.http.routers.nginx-secure.entrypoints=https"
            - "traefik.http.routers.nginx-secure.rule=Host(`${DOMAIN}`)"
            - "traefik.http.routers.nginx-secure.tls=true"
            - "traefik.http.routers.nginx-secure.tls.certresolver=letsencrypt"
            - "traefik.http.routers.nginx-secure.service=nginx"
            - "traefik.http.services.nginx.loadbalancer.server.port=80"
        networks:
            - proxy

    # ####################################################################################################
    # # DATABASE (MariaDB)
    # ####################################################################################################
    db:
        container_name: db
        image: mariadb:10.11
        ports:
            - 3306:3306
        volumes:
            - .docker/db/data:/var/lib/mysql
            - .docker/logs:/var/log/mysql
            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
            - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        networks:
            - proxy

    ####################################################################################################
    # Redis
    ####################################################################################################
    # redis:
    #     container_name: redis
    #     image: redis:latest
    #     command: redis-server --appendonly yes
    #     volumes:
    #     - .docker/redis/data:/data
    #     ports:
    #     - 6379:6379
    #     networks:
    #         - proxy

networks:
    proxy:
        external: true
