version: "3.5"
services:
  wemx:
    container_name: wemx
    restart: unless-stopped
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    ports:
      - 5173:5173
    volumes:
      - ./${APP_DIR}:/var/www:cached
      - ./.docker/php/install.sh:/usr/local/bin/install.sh
      - ./.docker/php/update.sh:/usr/local/bin/update.sh
      - ./.env:/usr/local/bin/.env
      - ./backups:/var/backups
    environment:
      APP_URL: ${APP_URL}
      DOMAIN: ${DOMAIN}
      DB_CONNECTION: mysql
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      LICENSE_KEY: ${LICENSE_KEY}
      USERNAME: ${USERNAME}
      PASSWORD: ${PASSWORD}
      EMAIL: ${EMAIL}
      FIRST_NAME: ${FIRST_NAME}
      LAST_NAME: ${LAST_NAME}
      FORCE_HTTPS: ${FORCE_HTTPS}
      LARAVEL_CLOUDFLARE_ENABLED: ${LARAVEL_CLOUDFLARE_ENABLED}
      VERSION: ${VERSION}
      TYPE: ${TYPE}
    networks:
      - proxy

networks:
  proxy:
    external: true
